### ISSUE TITLE
The "hmac" argument must be of type string

### ISSUE THREAD

**Issue by MathieuRS1** [thecreazy/chiccocoin#1]
Hi :)

Nice chiccocoin !! I have this error : The "hmac" argument must be of type string

On http://localhost:3000/mine

TypeError [ERR_INVALID_ARG_TYPE]: The "hmac" argument must be of type string
    at new Hmac (internal/crypto/hash.js:82:11)
    at Object.createHmac (crypto.js:122:10)
    at Blockchain.validProof (/home/mathieu/Bureau/nodejs/blockchain-test1/middleware/blockchain.js:51:30)
    at Blockchain.proofOfWork (/home/mathieu/Bureau/nodejs/blockchain-test1/middleware/blockchain.js:60:17)
    at Chiccocoin.mine (/home/mathieu/Bureau/nodejs/blockchain-test1/middleware/chiccocoin.js:22:35)
    at Layer.handle [as handle_request] (/home/mathieu/Bureau/nodejs/blockchain-test1/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/mathieu/Bureau/nodejs/blockchain-test1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/mathieu/Bureau/nodejs/blockchain-test1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/mathieu/Bureau/nodejs/blockchain-test1/node_modules/express/lib/router/layer.js:95:5)
    at /home/mathieu/Bureau/nodejs/blockchain-test1/node_modules/express/lib/router/index.js:281:22

Any idea ?

Thank you, 

Mathieu

**Comment by MathieuRS1** [comment]
Ok, .env don't come with repository download, It's ok 👍
